### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; 

### ISSUE THREAD

**Issue by jisungbin** [myinnos/AwesomeImagePicker#16]
My code :
sendImage.setOnClickListener(new View.OnClickListener() {
			public void onClick(View v) {
				try{
					Intent intent = new Intent(chat.this, AlbumSelectActivity.class);
					intent.putExtra(ConstantsCustomGallery.INTENT_EXTRA_LIMIT, REQ_CODE_SELECT_IMAGE);
					startActivityForResult(intent, ConstantsCustomGallery.REQUEST_CODE);
				}
				catch(Exception e){
					toast(e.toString());
				}
				alert.dismiss();
			}
		});

Error Log : 
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.sungbin.pubg.m.chatting-vVWfe3uWp2dJ2Bbtr5X6Tg==/base.apk)
at in.myinnos.awesomeimagepicker.adapter.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:60)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.AbsListView.obtainView(AbsListView.java:3189)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.GridView.onMeasure(GridView.java:1102)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.View.measure(View.java:23297)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.View.measure(View.java:23297)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.View.measure(View.java:23297)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.View.measure(View.java:23297)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at com.android.internal.policy.DecorView.onMeasure(DecorView.java:899)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.View.measure(View.java:23297)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2849)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1879)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2134)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1748)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7785)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.Choreographer.doCallbacks(Choreographer.java:723)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.Choreographer.doFrame(Choreographer.java:658)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.os.Handler.handleCallback(Handler.java:789)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:98)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.os.Looper.loop(Looper.java:164)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:6944)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at java.lang.reflect.Method.invoke(Native Method)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-27 15:58:09.054 27421 27421 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by sehsah** [comment]
+1

**Comment by nawaz4225** [comment]
+1

**Comment by subhadiprudra** [comment]
+1
