### ISSUE TITLE
Crash when change screen orientation

### ISSUE THREAD

**Issue by firdausmaulan** [myinnos/AwesomeImagePicker#4]
Crash when change screen orientation..

I've fix this issue, when I add this code in manifest.
`<activity
            android:name="in.myinnos.awesomeimagepicker.activities.AlbumSelectActivity"
            android:screenOrientation="portrait" />`
`<activity
            android:name="in.myinnos.awesomeimagepicker.activities.ImageSelectActivity"
            android:screenOrientation="portrait" />`

**Comment by myinnos** [comment]
Fixed in [v1.02](https://github.com/myinnos/AwesomeImagePicker/releases/tag/1.0.2)
