### ISSUE TITLE
Throws IllegalArgument exception in Lollipop

### ISSUE THREAD

**Issue by vihaarich** [myinnos/AwesomeImagePicker#5]
Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vitech.storiesofcommonman/in.myinnos.awesomeimagepicker.activities.AlbumSelectActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v7.widget.Toolbar$d instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/toolbar. Make sure other views do not use the same id.

Yes there was another toolbar with Id toolbar but the same gets thrown even after I changed its ID to tool_bar.  

This bug appears only in lollipop and it started appearing after i used progaurd.

**Comment by firdausmaulan** [comment]
Try to add theme NoActionBar on your manifest
`<activity
            android:name="in.myinnos.awesomeimagepicker.activities.AlbumSelectActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar" />
<activity
            android:name="in.myinnos.awesomeimagepicker.activities.ImageSelectActivity"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar" />`

**Comment by myinnos** [comment]
@vihaarich override NoActionBar theme in your manifest file for library classes(ref @firdausmaulan answer)

Fixed in [v1.02](https://github.com/myinnos/AwesomeImagePicker/releases/tag/1.0.2)
