### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Karljoones** [myinnos/AwesomeImagePicker#6]
First of all, thank you for making this. It's the first library of its kind that I found actually works with Marshmallow.

My only issue with it is the strings - is there a way for us to change them as a user of the library? I like to have my app ready for translation and this library would prevent some strings from being able to be translated. For example, the message that appears when the user selects too many photos.

Many thanks in advance.

**Comment by Karljoones** [comment]
I see that your previous release added support for multilanguage but there is no documentation on this. Are we able to make these translations ourselves?

**Comment by myinnos** [comment]
@Karljoones yes currently Arabic language added in string structure. currently am not focussing on Language translation. 

if our planning to add multiple languages please feel free to fork the repo to add multiple languages. i will pull it to master.
